-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.38-0ubuntu0.14.04.1 - (Ubuntu)
-- Server OS:                    debian-linux-gnu
-- HeidiSQL Version:             8.3.0.4694
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table db_wallofframe.products
CREATE TABLE IF NOT EXISTS `products` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `status_id` int(11) NOT NULL,
  `type_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `brand_id` int(11) NOT NULL,
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `content` text COLLATE utf8_unicode_ci NOT NULL,
  `excerpt` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `price` decimal(5,2) NOT NULL,
  `width` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `height` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `is_available` tinyint(1) NOT NULL,
  `views` int(11) NOT NULL,
  `image` text COLLATE utf8_unicode_ci NOT NULL,
  `image_type` enum('square','horizontal','vertical') COLLATE utf8_unicode_ci DEFAULT 'square',
  `image_original_type` enum('square','horizontal','vertical') COLLATE utf8_unicode_ci DEFAULT 'square',
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Dumping data for table db_wallofframe.products: ~32 rows (approximately)
/*!40000 ALTER TABLE `products` DISABLE KEYS */;
INSERT INTO `products` (`id`, `status_id`, `type_id`, `category_id`, `brand_id`, `title`, `content`, `excerpt`, `slug`, `price`, `width`, `height`, `is_available`, `views`, `image`, `image_type`, `image_original_type`, `created_at`, `updated_at`, `deleted_at`) VALUES
	(2, 4, 1, 2, 5, 'Edited Title 2', 'Cupiditate error quaerat recusandae id dolores rerum aliquam. Nihil placeat libero enim magnam nulla placeat neque. Quos et explicabo aliquid dolores ut. Hic maxime quas nulla possimus aut ex maiores aspernatur. Asperiores rerum hic vel molestias.\nSed quisquam et nobis in ad est aut. Debitis perspiciatis eum voluptas est inventore ab. Est expedita soluta qui similique. Optio eligendi facere odit ea. Rerum sed consequatur voluptatum nam.', 'Fugit quis recusandae ut quis et harum autem. Corporis qui veniam minus necessitatibus et eveniet ut', 'quis', 466.89, '32', '53', 1, 17, '21.jpg\r\n', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-13 06:41:28', NULL),
	(3, 3, 3, 1, 2, 'Vel Ipsa', 'Accusamus et neque sequi et dolore tempore. Reiciendis beatae quia quas ut eos qui itaque. Et ut in ipsum. Tempora ut ipsa architecto id omnis qui et. Harum et consequatur delectus rerum ipsa.\nSed doloribus aut adipisci consectetur unde consequatur. Id quidem aspernatur molestiae. Possimus dolorem quidem doloribus inventore et aut. Autem et eligendi quia sunt voluptates sequi.', 'Voluptates perspiciatis corporis est molestias odio ducimus. Ex atque harum nesciunt iste enim. Quia', 'vel-ipsa', 468.23, '490', '992', 1, 7, '1.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-13 06:15:39', NULL),
	(4, 3, 2, 1, 5, 'Illo Ut', 'Minus velit recusandae provident adipisci. Minus ut iste similique praesentium ea. Dolore quos qui aliquam id.\nIn aliquam inventore perferendis cum. Dolore voluptatum repellendus est omnis ea commodi. Cupiditate eius dolor dolor et. Porro blanditiis est doloremque et.\nExercitationem consequatur cumque recusandae optio. Odit vitae tempora aut cupiditate praesentium. Sunt id iure voluptatem occaecati quos. Tempora sit dignissimos quia perferendis explicabo dolor iste qui.', 'Corporis aliquam culpa hic. Aperiam sit qui illo est atque odio doloremque. Voluptatem labore minus', 'illo-ut', 149.48, '32', '248', 1, 4, '2.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-13 06:15:48', NULL),
	(5, 4, 2, 1, 5, 'Recusandae consequatur.', 'Illo expedita eligendi quibusdam ut incidunt assumenda doloremque. Eaque ab eaque nam quibusdam fuga enim voluptatem ducimus. Consequatur dolorem rerum vel enim exercitationem qui aspernatur. Officia occaecati non rerum sit temporibus officiis iure omnis.\nNostrum aliquid autem sed et. Cum nobis doloremque a aperiam. Qui consequatur iusto dolores et amet voluptatibus.\nEos natus sit temporibus ut. Aperiam reprehenderit quidem ex.', 'Ea dolorem sint ab vitae aut. Soluta voluptas voluptas ab rerum porro et. Doloribus id natus vel fuga et rem iusto.', 'recusandae-consequatur', 388.53, '485', '620', 1, 3, '3.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(6, 3, 1, 1, 3, 'Consequatur itaque.', 'Est quia reiciendis et fugiat officiis voluptatem modi. Ea ducimus veritatis aut vel sint facere sed doloremque. Quo temporibus voluptatem culpa unde beatae dicta. Iure beatae ab ut porro totam rerum.\nDolore quibusdam qui beatae nemo. Modi exercitationem consequatur quam qui aut. Qui veniam exercitationem molestiae rem est. Qui voluptate aut suscipit nisi et vitae corrupti. Rem excepturi soluta dolor necessitatibus.', 'Consequatur quod nihil fugiat. Modi eum ducimus ipsam fugit praesentium nesciunt maiores. Corrupti eligendi suscipit quisquam ipsam tenetur veniam.', 'consequatur-itaque', 196.42, '211', '957', 1, 2, '4.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(7, 4, 1, 3, 1, 'Qui recusandae.', 'Inventore ut quae accusamus. Ut perferendis aut eius optio a. Vel velit rem consequatur labore praesentium dolores. Hic occaecati itaque quasi beatae porro ut.\nMinus dolorem ea quam harum. Consequatur in officiis et dolorum sunt non ipsa atque.\nA nobis ut voluptatem aut aut excepturi aut autem. Cumque tempore aut itaque qui ducimus reiciendis. Ut asperiores non voluptatum at deleniti.', 'Provident facilis reiciendis iure quo repellendus similique accusantium. Iusto sunt aspernatur ex illo soluta et aut. Et consequatur rerum provident sint.', 'qui-recusandae', 239.78, '261', '126', 1, 2, '22.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-04 12:17:00', NULL),
	(8, 4, 1, 3, 2, 'Maiores.', 'Facere nihil sed nulla totam sequi atque quis. Odit delectus voluptates atque temporibus aut ad et.\nOfficia est accusantium dolor debitis voluptas quae. Modi impedit cum id voluptatem est rerum.\nQuis et possimus quae magni voluptatem aut reprehenderit. Et ullam enim porro libero. Dolore non dolor esse id accusantium quia.\nEst natus fugiat aut sed voluptas minus architecto. Animi odit delectus et. Aut at doloremque quae ratione. Quia earum dolor consequatur in fugiat et repellat.', 'Quia sit et alias possimus commodi animi voluptatum. Laborum quia possimus modi. Tempore maxime provident beatae odio. Provident et debitis quibusdam.', 'maiores', 293.26, '874', '874', 1, 6, '23.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 03:40:20', NULL),
	(9, 3, 2, 3, 5, 'Illo earum.', 'Voluptatem porro reprehenderit voluptatem veniam rerum id vitae. Dolorem voluptatem aut ratione non aperiam. Molestiae officiis qui et recusandae. Voluptas fugit omnis illo.\nVeniam harum quis aut eum aut qui accusamus optio. Beatae officia dolorem cumque excepturi. Autem maiores est fugiat qui. Illum aut nihil omnis est velit.\nUt voluptatem suscipit et et qui. Consequatur tenetur in aliquam repudiandae et. Vero iure maiores ut expedita. Error molestiae delectus nulla aut.', 'Omnis aut et qui eius ab vel. In impedit eius omnis alias dolores dolor delectus. Velit aspernatur nemo necessitatibus quis quas dolorum.', 'illo-earum', 111.09, '276', '76', 1, 3, '24.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-05 03:26:14', NULL),
	(13, 4, 2, 1, 5, 'Nulla.', 'Ea et aut alias earum deleniti. Tempora illum libero fugit quis eum natus est. Fugiat nobis nisi omnis aut eos qui.\nEius mollitia id in sed. Velit voluptas earum recusandae reprehenderit quo. Ut quis dolores nisi. Nam rem vero est et omnis temporibus. Ipsa quaerat dolores alias.\nConsequatur sint voluptatem accusamus. Rerum repudiandae nihil tenetur incidunt dolores id. Voluptate beatae laborum tenetur cumque nesciunt vitae.', 'Distinctio iure expedita quas libero earum voluptatem. Omnis et enim autem veniam aut quas deleniti. Deleniti perspiciatis aut tenetur doloribus.', 'nulla', 447.53, '168', '718', 1, 4, '5.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(15, 4, 3, 1, 4, 'Odit.', 'Qui et optio impedit qui minima rerum. Qui tempora soluta aliquam nemo error.\nVoluptatem harum dolorem dignissimos reprehenderit et necessitatibus. Quasi eos dolore ad earum. Fugit officiis amet et possimus distinctio et necessitatibus. Aut nam ut dolor corrupti culpa.\nQuis repellendus harum quae et officiis qui dolore. Officia omnis qui fuga explicabo molestiae. Consequatur sint quam est molestiae.', 'Magni officiis repudiandae fuga expedita sed. Qui voluptatem necessitatibus in iste quia deserunt saepe. Quis earum et quia labore suscipit eius sed quo.', 'odit', 316.76, '963', '968', 1, 1, '6.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(19, 3, 3, 1, 2, 'Et enim.', 'Minus autem eveniet doloremque molestiae. Adipisci consequuntur odio veniam saepe ea vitae. Aut ab suscipit error est. Maxime temporibus excepturi repudiandae voluptatem ut. Voluptas sit sunt praesentium adipisci cupiditate ut.\nUllam eos suscipit natus aut architecto facere. Consequatur temporibus quis blanditiis commodi corrupti. Earum nesciunt hic non veritatis repellat.', 'Debitis tempora natus inventore et placeat. Eum ut nostrum explicabo dolorem omnis occaecati.', 'et-enim', 350.57, '265', '692', 1, 0, '7.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(20, 4, 2, 1, 4, 'In Aspernatur', 'Cupiditate consectetur iure et consequatur. Dolores unde et sunt. Aut doloribus quas est hic neque aliquid beatae.\nEnim quod blanditiis in velit eligendi. Omnis quia quisquam suscipit magni omnis saepe quia. Dolor deleniti asperiores sit autem sit.\nLaudantium cupiditate laboriosam optio cumque rerum eum omnis. In error necessitatibus debitis sit. Alias incidunt occaecati blanditiis dolores aut consectetur. Architecto exercitationem rerum deserunt atque velit eveniet voluptate illum.', 'Qui facere sed et placeat dolores. Aut qui tempora possimus. Rerum dolorem beatae repellat unde quo.', 'in-aspernatur', 393.32, '438', '971', 1, 3, '8.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-13 06:15:55', NULL),
	(21, 4, 3, 1, 4, 'Odit.', 'Qui et optio impedit qui minima rerum. Qui tempora soluta aliquam nemo error.\nVoluptatem harum dolorem dignissimos reprehenderit et necessitatibus. Quasi eos dolore ad earum. Fugit officiis amet et possimus distinctio et necessitatibus. Aut nam ut dolor corrupti culpa.\nQuis repellendus harum quae et officiis qui dolore. Officia omnis qui fuga explicabo molestiae. Consequatur sint quam est molestiae.', 'Magni officiis repudiandae fuga expedita sed. Qui voluptatem necessitatibus in iste quia deserunt saepe. Quis earum et quia labore suscipit eius sed quo.', 'odit', 316.76, '963', '968', 1, 1, '9.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(22, 3, 3, 1, 6, 'Vel ipsa.', 'Accusamus et neque sequi et dolore tempore. Reiciendis beatae quia quas ut eos qui itaque. Et ut in ipsum. Tempora ut ipsa architecto id omnis qui et. Harum et consequatur delectus rerum ipsa.\nSed doloribus aut adipisci consectetur unde consequatur. Id quidem aspernatur molestiae. Possimus dolorem quidem doloribus inventore et aut. Autem et eligendi quia sunt voluptates sequi.', 'Voluptates perspiciatis corporis est molestias odio ducimus. Ex atque harum nesciunt iste enim. Quia hic et voluptatem voluptate fugit.', 'vel-ipsa', 468.23, '490', '992', 1, 5, '10.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 05:22:19', NULL),
	(23, 4, 2, 1, 6, 'In aspernatur.', 'Cupiditate consectetur iure et consequatur. Dolores unde et sunt. Aut doloribus quas est hic neque aliquid beatae.\nEnim quod blanditiis in velit eligendi. Omnis quia quisquam suscipit magni omnis saepe quia. Dolor deleniti asperiores sit autem sit.\nLaudantium cupiditate laboriosam optio cumque rerum eum omnis. In error necessitatibus debitis sit. Alias incidunt occaecati blanditiis dolores aut consectetur. Architecto exercitationem rerum deserunt atque velit eveniet voluptate illum.', 'Qui facere sed et placeat dolores. Aut qui tempora possimus. Rerum dolorem beatae repellat unde quo. Quia sit beatae et vitae dolor.', 'in-aspernatur', 393.32, '438', '971', 1, 2, '11.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 08:47:14', NULL),
	(24, 4, 2, 1, 6, 'In aspernatur.', 'Cupiditate consectetur iure et consequatur. Dolores unde et sunt. Aut doloribus quas est hic neque aliquid beatae.\nEnim quod blanditiis in velit eligendi. Omnis quia quisquam suscipit magni omnis saepe quia. Dolor deleniti asperiores sit autem sit.\nLaudantium cupiditate laboriosam optio cumque rerum eum omnis. In error necessitatibus debitis sit. Alias incidunt occaecati blanditiis dolores aut consectetur. Architecto exercitationem rerum deserunt atque velit eveniet voluptate illum.', 'Qui facere sed et placeat dolores. Aut qui tempora possimus. Rerum dolorem beatae repellat unde quo. Quia sit beatae et vitae dolor.', 'in-aspernatur', 393.32, '438', '971', 1, 2, '12.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 07:01:48', NULL),
	(25, 4, 2, 1, 6, 'In aspernatur.', 'Cupiditate consectetur iure et consequatur. Dolores unde et sunt. Aut doloribus quas est hic neque aliquid beatae.\nEnim quod blanditiis in velit eligendi. Omnis quia quisquam suscipit magni omnis saepe quia. Dolor deleniti asperiores sit autem sit.\nLaudantium cupiditate laboriosam optio cumque rerum eum omnis. In error necessitatibus debitis sit. Alias incidunt occaecati blanditiis dolores aut consectetur. Architecto exercitationem rerum deserunt atque velit eveniet voluptate illum.', 'Qui facere sed et placeat dolores. Aut qui tempora possimus. Rerum dolorem beatae repellat unde quo. Quia sit beatae et vitae dolor.', 'in-aspernatur', 393.32, '438', '971', 1, 1, '13.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 06:20:21', NULL),
	(26, 4, 2, 1, 5, 'Recusandae consequatur.', 'Illo expedita eligendi quibusdam ut incidunt assumenda doloremque. Eaque ab eaque nam quibusdam fuga enim voluptatem ducimus. Consequatur dolorem rerum vel enim exercitationem qui aspernatur. Officia occaecati non rerum sit temporibus officiis iure omnis.\nNostrum aliquid autem sed et. Cum nobis doloremque a aperiam. Qui consequatur iusto dolores et amet voluptatibus.\nEos natus sit temporibus ut. Aperiam reprehenderit quidem ex.', 'Ea dolorem sint ab vitae aut. Soluta voluptas voluptas ab rerum porro et. Doloribus id natus vel fuga et rem iusto.', 'recusandae-consequatur', 388.53, '485', '620', 1, 3, '14.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-06 11:20:30', NULL),
	(27, 3, 2, 1, 10, 'Illo ut.', 'Minus velit recusandae provident adipisci. Minus ut iste similique praesentium ea. Dolore quos qui aliquam id.\nIn aliquam inventore perferendis cum. Dolore voluptatum repellendus est omnis ea commodi. Cupiditate eius dolor dolor et. Porro blanditiis est doloremque et.\nExercitationem consequatur cumque recusandae optio. Odit vitae tempora aut cupiditate praesentium. Sunt id iure voluptatem occaecati quos. Tempora sit dignissimos quia perferendis explicabo dolor iste qui.', 'Corporis aliquam culpa hic. Aperiam sit qui illo est atque odio doloremque. Voluptatem labore minus in eos tempora explicabo assumenda debitis.', 'illo-ut', 149.48, '32', '248', 1, 1, '15.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(28, 4, 2, 1, 5, 'Nulla.', 'Ea et aut alias earum deleniti. Tempora illum libero fugit quis eum natus est. Fugiat nobis nisi omnis aut eos qui.\nEius mollitia id in sed. Velit voluptas earum recusandae reprehenderit quo. Ut quis dolores nisi. Nam rem vero est et omnis temporibus. Ipsa quaerat dolores alias.\nConsequatur sint voluptatem accusamus. Rerum repudiandae nihil tenetur incidunt dolores id. Voluptate beatae laborum tenetur cumque nesciunt vitae.', 'Distinctio iure expedita quas libero earum voluptatem. Omnis et enim autem veniam aut quas deleniti. Deleniti perspiciatis aut tenetur doloribus.', 'nulla', 447.53, '168', '718', 1, 1, '16.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 08:19:26', NULL),
	(29, 4, 2, 1, 5, 'Nulla.', 'Ea et aut alias earum deleniti. Tempora illum libero fugit quis eum natus est. Fugiat nobis nisi omnis aut eos qui.\nEius mollitia id in sed. Velit voluptas earum recusandae reprehenderit quo. Ut quis dolores nisi. Nam rem vero est et omnis temporibus. Ipsa quaerat dolores alias.\nConsequatur sint voluptatem accusamus. Rerum repudiandae nihil tenetur incidunt dolores id. Voluptate beatae laborum tenetur cumque nesciunt vitae.', 'Distinctio iure expedita quas libero earum voluptatem. Omnis et enim autem veniam aut quas deleniti. Deleniti perspiciatis aut tenetur doloribus.', 'nulla', 447.53, '168', '718', 1, 0, '17.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(30, 3, 1, 1, 3, 'Consequatur itaque.', 'Est quia reiciendis et fugiat officiis voluptatem modi. Ea ducimus veritatis aut vel sint facere sed doloremque. Quo temporibus voluptatem culpa unde beatae dicta. Iure beatae ab ut porro totam rerum.\nDolore quibusdam qui beatae nemo. Modi exercitationem consequatur quam qui aut. Qui veniam exercitationem molestiae rem est. Qui voluptate aut suscipit nisi et vitae corrupti. Rem excepturi soluta dolor necessitatibus.', 'Consequatur quod nihil fugiat. Modi eum ducimus ipsam fugit praesentium nesciunt maiores. Corrupti eligendi suscipit quisquam ipsam tenetur veniam.', 'consequatur-itaque', 196.42, '211', '957', 1, 1, '18.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 08:15:37', NULL),
	(31, 3, 1, 1, 3, 'Consequatur itaque.', 'Est quia reiciendis et fugiat officiis voluptatem modi. Ea ducimus veritatis aut vel sint facere sed doloremque. Quo temporibus voluptatem culpa unde beatae dicta. Iure beatae ab ut porro totam rerum.\nDolore quibusdam qui beatae nemo. Modi exercitationem consequatur quam qui aut. Qui veniam exercitationem molestiae rem est. Qui voluptate aut suscipit nisi et vitae corrupti. Rem excepturi soluta dolor necessitatibus.', 'Consequatur quod nihil fugiat. Modi eum ducimus ipsam fugit praesentium nesciunt maiores. Corrupti eligendi suscipit quisquam ipsam tenetur veniam.', 'consequatur-itaque', 196.42, '211', '957', 1, 0, '19.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 04:10:02', NULL),
	(32, 3, 3, 1, 2, 'Et enim.', 'Minus autem eveniet doloremque molestiae. Adipisci consequuntur odio veniam saepe ea vitae. Aut ab suscipit error est. Maxime temporibus excepturi repudiandae voluptatem ut. Voluptas sit sunt praesentium adipisci cupiditate ut.\nUllam eos suscipit natus aut architecto facere. Consequatur temporibus quis blanditiis commodi corrupti. Earum nesciunt hic non veritatis repellat.', 'Debitis tempora natus inventore et placeat. Eum ut nostrum explicabo dolorem omnis occaecati.', 'et-enim', 350.57, '265', '692', 1, 1, '20.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-05 08:17:33', NULL),
	(33, 3, 2, 3, 5, 'Illo earum.', 'Voluptatem porro reprehenderit voluptatem veniam rerum id vitae. Dolorem voluptatem aut ratione non aperiam. Molestiae officiis qui et recusandae. Voluptas fugit omnis illo.\nVeniam harum quis aut eum aut qui accusamus optio. Beatae officia dolorem cumque excepturi. Autem maiores est fugiat qui. Illum aut nihil omnis est velit.\nUt voluptatem suscipit et et qui. Consequatur tenetur in aliquam repudiandae et. Vero iure maiores ut expedita. Error molestiae delectus nulla aut.', 'Omnis aut et qui eius ab vel. In impedit eius omnis alias dolores dolor delectus. Velit aspernatur nemo necessitatibus quis quas dolorum.', 'illo-earum', 111.09, '276', '76', 1, 3, '25.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-05 03:26:14', NULL),
	(34, 4, 1, 3, 1, 'Qui recusandae.', 'Inventore ut quae accusamus. Ut perferendis aut eius optio a. Vel velit rem consequatur labore praesentium dolores. Hic occaecati itaque quasi beatae porro ut.\nMinus dolorem ea quam harum. Consequatur in officiis et dolorum sunt non ipsa atque.\nA nobis ut voluptatem aut aut excepturi aut autem. Cumque tempore aut itaque qui ducimus reiciendis. Ut asperiores non voluptatum at deleniti.', 'Provident facilis reiciendis iure quo repellendus similique accusantium. Iusto sunt aspernatur ex illo soluta et aut. Et consequatur rerum provident sint.', 'qui-recusandae', 239.78, '261', '126', 1, 2, '26.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-04 12:17:00', NULL),
	(35, 4, 1, 3, 2, 'Maiores.', 'Facere nihil sed nulla totam sequi atque quis. Odit delectus voluptates atque temporibus aut ad et.\nOfficia est accusantium dolor debitis voluptas quae. Modi impedit cum id voluptatem est rerum.\nQuis et possimus quae magni voluptatem aut reprehenderit. Et ullam enim porro libero. Dolore non dolor esse id accusantium quia.\nEst natus fugiat aut sed voluptas minus architecto. Animi odit delectus et. Aut at doloremque quae ratione. Quia earum dolor consequatur in fugiat et repellat.', 'Quia sit et alias possimus commodi animi voluptatum. Laborum quia possimus modi. Tempore maxime provident beatae odio. Provident et debitis quibusdam.', 'maiores', 293.26, '874', '874', 1, 6, '27.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-05 03:40:20', NULL),
	(36, 3, 2, 3, 5, 'Illo earum.', 'Voluptatem porro reprehenderit voluptatem veniam rerum id vitae. Dolorem voluptatem aut ratione non aperiam. Molestiae officiis qui et recusandae. Voluptas fugit omnis illo.\nVeniam harum quis aut eum aut qui accusamus optio. Beatae officia dolorem cumque excepturi. Autem maiores est fugiat qui. Illum aut nihil omnis est velit.\nUt voluptatem suscipit et et qui. Consequatur tenetur in aliquam repudiandae et. Vero iure maiores ut expedita. Error molestiae delectus nulla aut.', 'Omnis aut et qui eius ab vel. In impedit eius omnis alias dolores dolor delectus. Velit aspernatur nemo necessitatibus quis quas dolorum.', 'illo-earum', 111.09, '276', '76', 1, 3, '28.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-05 03:26:14', NULL),
	(37, 4, 1, 3, 1, 'Qui recusandae.', 'Inventore ut quae accusamus. Ut perferendis aut eius optio a. Vel velit rem consequatur labore praesentium dolores. Hic occaecati itaque quasi beatae porro ut.\nMinus dolorem ea quam harum. Consequatur in officiis et dolorum sunt non ipsa atque.\nA nobis ut voluptatem aut aut excepturi aut autem. Cumque tempore aut itaque qui ducimus reiciendis. Ut asperiores non voluptatum at deleniti.', 'Provident facilis reiciendis iure quo repellendus similique accusantium. Iusto sunt aspernatur ex illo soluta et aut. Et consequatur rerum provident sint.', 'qui-recusandae', 239.78, '261', '126', 1, 2, '29.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-04 12:17:00', NULL),
	(38, 4, 1, 3, 2, 'Maiores.', 'Facere nihil sed nulla totam sequi atque quis. Odit delectus voluptates atque temporibus aut ad et.\nOfficia est accusantium dolor debitis voluptas quae. Modi impedit cum id voluptatem est rerum.\nQuis et possimus quae magni voluptatem aut reprehenderit. Et ullam enim porro libero. Dolore non dolor esse id accusantium quia.\nEst natus fugiat aut sed voluptas minus architecto. Animi odit delectus et. Aut at doloremque quae ratione. Quia earum dolor consequatur in fugiat et repellat.', 'Quia sit et alias possimus commodi animi voluptatum. Laborum quia possimus modi. Tempore maxime provident beatae odio. Provident et debitis quibusdam.', 'maiores', 293.26, '874', '874', 1, 7, '30.jpg', 'square', 'vertical', '2014-12-18 07:56:32', '2015-01-08 08:10:05', NULL),
	(39, 4, 1, 3, 1, 'Qui recusandae.', 'Inventore ut quae accusamus. Ut perferendis aut eius optio a. Vel velit rem consequatur labore praesentium dolores. Hic occaecati itaque quasi beatae porro ut.\nMinus dolorem ea quam harum. Consequatur in officiis et dolorum sunt non ipsa atque.\nA nobis ut voluptatem aut aut excepturi aut autem. Cumque tempore aut itaque qui ducimus reiciendis. Ut asperiores non voluptatum at deleniti.', 'Provident facilis reiciendis iure quo repellendus similique accusantium. Iusto sunt aspernatur ex illo soluta et aut. Et consequatur rerum provident sint.', 'qui-recusandae', 239.78, '261', '126', 1, 3, '31.jpg', 'square', 'horizontal', '2014-12-18 07:56:32', '2015-01-08 08:06:46', NULL),
	(40, 5, 1, 1, 1, '', '', '', '', 0.00, '2000', '2000', 1, 0, 'LQw0WY9ck3VzZ9jZPmtL.jpg', 'square', 'square', '2015-01-13 07:09:53', '2015-01-13 18:24:53', '2015-01-13 18:24:53');
/*!40000 ALTER TABLE `products` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
